# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/doctopus/Documents/code/renderer

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/doctopus/Documents/code/renderer

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/usr/bin/ctest $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/doctopus/Documents/code/renderer/CMakeFiles /home/doctopus/Documents/code/renderer//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/doctopus/Documents/code/renderer/CMakeFiles 0
.PHONY : all

# The main codegen target
codegen: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/doctopus/Documents/code/renderer/CMakeFiles /home/doctopus/Documents/code/renderer//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 codegen
	$(CMAKE_COMMAND) -E cmake_progress_start /home/doctopus/Documents/code/renderer/CMakeFiles 0
.PHONY : codegen

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named RendererApp

# Build rule for target.
RendererApp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 RendererApp
.PHONY : RendererApp

# fast build rule for target.
RendererApp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RendererApp.dir/build.make CMakeFiles/RendererApp.dir/build
.PHONY : RendererApp/fast

src/Cube.o: src/Cube.cpp.o
.PHONY : src/Cube.o

# target to build an object file
src/Cube.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RendererApp.dir/build.make CMakeFiles/RendererApp.dir/src/Cube.cpp.o
.PHONY : src/Cube.cpp.o

src/Cube.i: src/Cube.cpp.i
.PHONY : src/Cube.i

# target to preprocess a source file
src/Cube.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RendererApp.dir/build.make CMakeFiles/RendererApp.dir/src/Cube.cpp.i
.PHONY : src/Cube.cpp.i

src/Cube.s: src/Cube.cpp.s
.PHONY : src/Cube.s

# target to generate assembly for a file
src/Cube.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RendererApp.dir/build.make CMakeFiles/RendererApp.dir/src/Cube.cpp.s
.PHONY : src/Cube.cpp.s

src/Matrix.o: src/Matrix.cpp.o
.PHONY : src/Matrix.o

# target to build an object file
src/Matrix.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RendererApp.dir/build.make CMakeFiles/RendererApp.dir/src/Matrix.cpp.o
.PHONY : src/Matrix.cpp.o

src/Matrix.i: src/Matrix.cpp.i
.PHONY : src/Matrix.i

# target to preprocess a source file
src/Matrix.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RendererApp.dir/build.make CMakeFiles/RendererApp.dir/src/Matrix.cpp.i
.PHONY : src/Matrix.cpp.i

src/Matrix.s: src/Matrix.cpp.s
.PHONY : src/Matrix.s

# target to generate assembly for a file
src/Matrix.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RendererApp.dir/build.make CMakeFiles/RendererApp.dir/src/Matrix.cpp.s
.PHONY : src/Matrix.cpp.s

src/MatrixUtils.o: src/MatrixUtils.cpp.o
.PHONY : src/MatrixUtils.o

# target to build an object file
src/MatrixUtils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RendererApp.dir/build.make CMakeFiles/RendererApp.dir/src/MatrixUtils.cpp.o
.PHONY : src/MatrixUtils.cpp.o

src/MatrixUtils.i: src/MatrixUtils.cpp.i
.PHONY : src/MatrixUtils.i

# target to preprocess a source file
src/MatrixUtils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RendererApp.dir/build.make CMakeFiles/RendererApp.dir/src/MatrixUtils.cpp.i
.PHONY : src/MatrixUtils.cpp.i

src/MatrixUtils.s: src/MatrixUtils.cpp.s
.PHONY : src/MatrixUtils.s

# target to generate assembly for a file
src/MatrixUtils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RendererApp.dir/build.make CMakeFiles/RendererApp.dir/src/MatrixUtils.cpp.s
.PHONY : src/MatrixUtils.cpp.s

src/Object3D.o: src/Object3D.cpp.o
.PHONY : src/Object3D.o

# target to build an object file
src/Object3D.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RendererApp.dir/build.make CMakeFiles/RendererApp.dir/src/Object3D.cpp.o
.PHONY : src/Object3D.cpp.o

src/Object3D.i: src/Object3D.cpp.i
.PHONY : src/Object3D.i

# target to preprocess a source file
src/Object3D.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RendererApp.dir/build.make CMakeFiles/RendererApp.dir/src/Object3D.cpp.i
.PHONY : src/Object3D.cpp.i

src/Object3D.s: src/Object3D.cpp.s
.PHONY : src/Object3D.s

# target to generate assembly for a file
src/Object3D.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RendererApp.dir/build.make CMakeFiles/RendererApp.dir/src/Object3D.cpp.s
.PHONY : src/Object3D.cpp.s

src/Shader.o: src/Shader.cpp.o
.PHONY : src/Shader.o

# target to build an object file
src/Shader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RendererApp.dir/build.make CMakeFiles/RendererApp.dir/src/Shader.cpp.o
.PHONY : src/Shader.cpp.o

src/Shader.i: src/Shader.cpp.i
.PHONY : src/Shader.i

# target to preprocess a source file
src/Shader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RendererApp.dir/build.make CMakeFiles/RendererApp.dir/src/Shader.cpp.i
.PHONY : src/Shader.cpp.i

src/Shader.s: src/Shader.cpp.s
.PHONY : src/Shader.s

# target to generate assembly for a file
src/Shader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RendererApp.dir/build.make CMakeFiles/RendererApp.dir/src/Shader.cpp.s
.PHONY : src/Shader.cpp.s

src/Vector.o: src/Vector.cpp.o
.PHONY : src/Vector.o

# target to build an object file
src/Vector.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RendererApp.dir/build.make CMakeFiles/RendererApp.dir/src/Vector.cpp.o
.PHONY : src/Vector.cpp.o

src/Vector.i: src/Vector.cpp.i
.PHONY : src/Vector.i

# target to preprocess a source file
src/Vector.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RendererApp.dir/build.make CMakeFiles/RendererApp.dir/src/Vector.cpp.i
.PHONY : src/Vector.cpp.i

src/Vector.s: src/Vector.cpp.s
.PHONY : src/Vector.s

# target to generate assembly for a file
src/Vector.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RendererApp.dir/build.make CMakeFiles/RendererApp.dir/src/Vector.cpp.s
.PHONY : src/Vector.cpp.s

src/Window.o: src/Window.cpp.o
.PHONY : src/Window.o

# target to build an object file
src/Window.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RendererApp.dir/build.make CMakeFiles/RendererApp.dir/src/Window.cpp.o
.PHONY : src/Window.cpp.o

src/Window.i: src/Window.cpp.i
.PHONY : src/Window.i

# target to preprocess a source file
src/Window.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RendererApp.dir/build.make CMakeFiles/RendererApp.dir/src/Window.cpp.i
.PHONY : src/Window.cpp.i

src/Window.s: src/Window.cpp.s
.PHONY : src/Window.s

# target to generate assembly for a file
src/Window.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RendererApp.dir/build.make CMakeFiles/RendererApp.dir/src/Window.cpp.s
.PHONY : src/Window.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RendererApp.dir/build.make CMakeFiles/RendererApp.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RendererApp.dir/build.make CMakeFiles/RendererApp.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RendererApp.dir/build.make CMakeFiles/RendererApp.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... codegen"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... RendererApp"
	@echo "... src/Cube.o"
	@echo "... src/Cube.i"
	@echo "... src/Cube.s"
	@echo "... src/Matrix.o"
	@echo "... src/Matrix.i"
	@echo "... src/Matrix.s"
	@echo "... src/MatrixUtils.o"
	@echo "... src/MatrixUtils.i"
	@echo "... src/MatrixUtils.s"
	@echo "... src/Object3D.o"
	@echo "... src/Object3D.i"
	@echo "... src/Object3D.s"
	@echo "... src/Shader.o"
	@echo "... src/Shader.i"
	@echo "... src/Shader.s"
	@echo "... src/Vector.o"
	@echo "... src/Vector.i"
	@echo "... src/Vector.s"
	@echo "... src/Window.o"
	@echo "... src/Window.i"
	@echo "... src/Window.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

